variables:
  Horton.Repo: $(Build.Repository.Uri)
  Horton.Commit: $(Build.SourceBranch)

name: $(BuildID)_$(Horton.Commit)_$(BuildDefinitionName)
variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)
jobs:
- template: templates/jobs-gate-c.yaml

parameters:
  repo: ''
  commit: ''
  job_tag: 'linux'

jobs:
- job: 'build_${{ parameters.job_tag }}_container'
  steps:
  
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'
  
  - powershell: |

      $NormalizedRepo=$env:Repo
      if ($NormalizedRepo -like 'https://github.com/*') {
        $NormalizedRepo=$NormalizedRepo.Substring('https://github.com/'.length)
      }
      Write-Host "##vso[task.setvariable variable=normalizedRepo]${NormalizedRepo}"
      Write-Host "normalizedRepo=${NormalizedRepo}"
    displayName: Removing github.com from repo name if necessary
    env:
      Repo: ${{ parameters.repo }}
    ignoreLASTEXITCODE: false
    errorActionPreference: Stop
    failOnStderr: true
  
  - script: |
      python3 $(Horton.FrameworkRoot)/pyscripts/build_docker_image.py --repo ${NormalizedRepo}  --commit ${{ parameters.commit }} 
    displayName: "build docker image ${{ parameters.language }}"
    condition: and(succeeded())
    env: 
      IOTHUB_E2E_REPO_ADDRESS: $(IOTHUB-E2E-REPO-ADDRESS)
      IOTHUB_E2E_REPO_USER: $(IOTHUB-E2E-REPO-USER)
      IOTHUB_E2E_REPO_PASSWORD: $(IOTHUB-E2E-REPO-PASSWORD)
      NormalizedRepo: $(NormalizedRepo)
  - task: CopyFiles@2
    displayName: 'Copy source tar to artifact staging'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/source_artifacts'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: and(
        always(), 
        eq('yes')
        )

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
    condition: always()


- job: 'Run Raspi E2E Tests'
  steps:
  
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: drop
      itemPattern: 'drop/**/*e2e_exe'
  
  - script: |
    # Write your commands here
    sudo -E ~/env_vars.sh
    chmod -R 777 drop/
    drop/cmake/iothub_client/tests/iothubclient_mqtt_e2e/iothubclient_mqtt_e2e_exe
    call jenkins\collect_results.cmd raspi

    workingDirectory: '$(System.ArtifactsDirectory)'

    displayName: 'Command Line Script'

    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish Test Results "**/results-junit.xml"'
    inputs:
      testResultsFiles: "**/results-junit.xml"
      testRunTitle: 'raspberry pi'
