variables:
  Horton.Repo: $(Build.Repository.Uri)
  Horton.Commit: $(Build.SourceBranch)
  Horton.FrameworkRoot: $(Build.SourcesDirectory)


jobs:
- job: 'Cross_Compile_SDK_To_Raspi'
  steps:
  
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'
  
  - powershell: |
      $NormalizedRepo=$env:Repo
      if ($NormalizedRepo -like 'https://github.com/*') {
        $NormalizedRepo=$NormalizedRepo.Substring('https://github.com/'.length)
      }
      Write-Host "##vso[task.setvariable variable=normalizedRepo]${NormalizedRepo}"
      Write-Host "normalizedRepo=${NormalizedRepo}"
    displayName: Removing github.com from repo name if necessary
    env:
      Repo: $(Horton.Repo)
    ignoreLASTEXITCODE: false
    errorActionPreference: Stop
    failOnStderr: true
  
  - script: |
      python3 $(Horton.FrameworkRoot)/pyscripts/build_docker_image.py --repo ${NormalizedRepo}  --commit $(Horton.Commit) 
    displayName: "build raspi-c docker image"
    condition: and(succeeded())
    env: 
      IOTHUB_E2E_REPO_ADDRESS: $(IOTHUB-E2E-REPO-ADDRESS)
      IOTHUB_E2E_REPO_USER: $(IOTHUB-E2E-REPO-USER)
      IOTHUB_E2E_REPO_PASSWORD: $(IOTHUB-E2E-REPO-PASSWORD)
      NormalizedRepo: $(NormalizedRepo)

  - task: CopyFiles@2
    displayName: 'Copy source tar to artifact staging'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/source_artifacts'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: and(
        always(), 
        eq('yes')
        )

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
    condition: always()
